version: '3.8'

services:
  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1-node-stripe
      - app2-flask
      - app3-express
    restart: unless-stopped

  app1-node-stripe:
    build: ./app1-node-stripe
    expose:
      - "3000"
    environment:
      - STRIPE_SECRET_KEY=sk_test_1234567890abcdef
    restart: unless-stopped

  app2-flask:
    build: ./app2-flask
    expose:
      - "5000"
    restart: unless-stopped

  app3-express:
    build: ./app3-express
    expose:
      - "8080"
    restart: unless-stopped

  static-app:
    build: ./static-app
    ports:
      - "8081:80"  # Accessible directement
    restart: unless-stopped
